import React,{useMemo,useState}from"react";
import{createRoot}from"react-dom/client";
import{Sparkles,Copy,CheckCircle2,AlertCircle,Globe2,Waves,Film,Train,PawPrint,Info,Shirt,Heart,Image as ImageIcon,Link as LinkIcon,X}from"lucide-react";
import"./style.css";

const sisterSiteUrl="https://yuyupm.vercel.app/";
const heroImageUrl="/top.png";
const opt=a=>a.map(([id,label,prompt,extra])=>({id,label,prompt,...(extra||{})}));
const by=(a,id)=>a.find(x=>x.id===id)||a[0];

const identity=`アップロードされたペットの顔・表情・毛色・模様・目の形・鼻と口まわり・耳の位置・毛並み・体格を最優先で保持してください。犬・猫・ハムスターなど、元写真のペットの種類と本人らしさを守り、別の子に変えないでください。白目・まつ毛・別の口元など元写真にない要素は追加しないでください。`;
const dream=`現実そのままではなく、夢の中のように美しく理想化された風景にしてください。雑多な現実感、生活感、汚れ、暗さ、不要な看板、古びた質感は避けてください。ペットの顔が主役としてはっきり見える構図にしてください。`;
const travelRule=`旅行カテゴリは「夢の観光ポスター構図」。場所らしさが分かる背景量と、ペットの顔がちゃんと見える距離を両立してください。近すぎてただの壁や階段にならず、遠すぎてペットが豆粒にならないように。現実の建物配置は完全再現不要。色・建築特徴・空気感を守りつつ、ペットが一番可愛く見える夢世界として再構成してください。`;
const movieRule=`映画ポスター風では、元写真の体型・ポーズ・四足姿勢はコピーしないでください。体は固定された可愛いマスコット人形風の直立ボディ。腰が後ろに出た犬の二足立ちは禁止。実在映画ロゴやタイトルは再現せず、架空タイトルとして扱ってください。`;
const animalRule=`動物たちは清潔で優しく夢の世界のように理想化してください。ただの森・草原・単色背景は禁止。選んだ動物に最も似合う夢背景を自動生成してください。キリン・馬・シマウマ・象は首や脚を長くしすぎず丸いぬいぐるみ寄り。恐竜は怖くせず絵本のように。`;
const kigurumiRule=`きぐるみ時は首から下を完全に丸いぬいぐるみ体型にしてください。元写真の4本脚姿勢は参照しすぎず、ころころした赤ちゃんぬいぐるみのような丸い胴体・短い手足にしてください。手先・足先まできぐるみで覆い、顔だけ本人が見えている状態にしてください。高級感のあるふわふわフェイクファーで、安っぽい化繊・スポンジ感は禁止。`;
const darkRule=`黒い子・濃い茶色の子・グレー系の子でも背景や全体の色調を暗く引きずらないでください。ペット本来の毛色は保ちつつ、背景は選んだ世界観どおり明るく、透明感と清潔感を維持してください。`;

const light=opt([
["auto","おまかせ","選んだ世界観に一番似合う光へ自動調整してください。"],["day","明るい昼","明るい昼の自然光で晴れやかに。"],["sunset","夕方","夕方の光で暗くしすぎず温かく幻想的に。"],["night","夜でも顔明るく","夜景でもペットの顔はやわらかく明るく。"]]);
const ratios=opt([["square","1:1 正方形","1:1の正方形構図。"],["r45","4:5 縦長","Instagram投稿向け4:5縦長構図。"],["r916","9:16 縦長","Instagramストーリー・リール向け9:16縦長構図。"],["r169","16:9 横長","16:9横長構図。"]]);
const paper=opt([["sns","通常SNS比率","通常SNS向け。"],["a4","A4","A4印刷向け比率。"],["b5","JIS-B5","JIS-B5印刷向け比率。"],["postcard","はがき","はがきサイズ向け比率。"]]);
const dirs=opt([["portrait","縦","縦向き。"],["landscape","横","横向き。"]]);

const categories=[
{id:"travel",label:"夢の世界旅行",icon:Globe2,description:"うちの子と夢の観光ポスター構図。",templates:opt([
["mykonos","ミコノス島風","白い階段、真っ白な建物、濃い青い丸屋根、青いドア、ターコイズブルーの海。禿山や茶色い岩山、雑多な観光地感は目立たせない。"],
["mont","モンサンミッシェル風","海に浮かぶ修道院のような壮大な建築。ペットは手前、遠景に建築全体。"],
["venice","ベネチア風","運河、ゴンドラ、クラシカルな建物、きらめく水面。"],["kyoto","京都風","石畳、和の建築、庭園、桜や紅葉。上品で静かな京都風。"],
["paris","パリ風","エッフェル塔や街灯、上品なカフェ通りを思わせる夢のパリ風。"],["london","ロンドン風","赤い電話ボックス、時計塔、明るく上品なロンドン風。"],
["alsace","アルザス風","木組みの家、花いっぱいの窓辺、石畳の小道。"],["petite","ラ・プチ・ヴェニス風","運河、花飾り、カラフルで可愛い家並み。"],
["romantic","ロマンチック街道風","石畳、絵本のような中世ヨーロッパ街並み。"],["castle","ノイシュバンシュタイン城風","白いおとぎ話のお城、山や森。"],
["taj","タージマハル風","白大理石の建築と水面反射。左右対称の美しい構図。"],["bali","バリ島寺院風","湖や水辺に浮かぶ美しいバリ島寺院風。"],
["uyuni","ウユニ塩湖風","鏡のような水面に空が映る超広角の美しい空と反射。"],["aurora","オーロラの国風","美しいオーロラと雪景色。夜でも顔は明るく。"],
["burano","ブラーノ島風","カラフルな家並みと運河。少し離れた運河沿い構図。"],["guanajuato","グアナファト風","丘に広がるカラフルな街並み。高台から少し見下ろす構図。"],
["cordoba","コルドバのパティオ風","白壁の中庭、アーチ、壁一面の鉢花、石畳。",{colorPresets:true}],
["custom_place","自由記入の場所","ユーザー指定の場所を夢の観光ポスター構図で理想化。場所以外の指定は無視。",{customPlace:true}]
])},
{id:"summer",label:"夏・海・水中",icon:Waves,description:"海・花火・水中・夏リゾート。",templates:opt([
["beach","夢のビーチリゾート","白い砂浜、透明なターコイズブルーの海、青空。"],["villa","水上コテージ","透明な海、白い桟橋、美しい水上コテージ、水上ヴィラ、南国リゾート感。"],
["fireworks","夏の花火","夏の夜空に花火。夜でも顔は暗くしない。",{fireworks:true}],["underwater","水中世界","透明な海、熱帯魚、サンゴ礁、きらめく水面光。"],["river","川遊び","澄んだ川の浅瀬で可愛く遊ぶ夏風景。"]])},
{id:"vehicle",label:"乗り物系",icon:Train,description:"ペットサイズの夢の乗り物。",templates:opt([
["sl","おもちゃのSL","可愛いおもちゃのSL機関車。"],["retro_airplane","レトロ飛行機","可愛いレトロ飛行機。"],["balloon","気球","可愛い気球で空を旅する。"],["sidecar","サイドカー","可愛いレトロなサイドカー。"],["flying_bike","未来の空飛ぶバイク","丸く安全なおもちゃ感のある未来の空飛ぶバイク。"],["flying_car","未来の空飛ぶ車","夢の都市や空を旅する未来の空飛ぶ車。"],["race_cart","おもちゃのレースカート","カラフルで可愛いおもちゃのレースカート。"],["cloud_car","雲の上を走る小さな車","雲の上を小さな可愛い車で走る夢のドライブ。"],["space_car","宇宙船風ミニカー","丸い宇宙船風ミニカーで星空を旅する。"],["custom_vehicle","自由記入の乗り物","自由記入の乗り物を安全で可愛い夢の乗り物にする。",{customVehicle:true}]])},
{id:"movie",label:"映画ポスター風",icon:Film,description:"構図・服・体型固定。顔と毛色だけ本人化。",templates:opt([
["ship","豪華客船ロマンス風","豪華客船を舞台にしたロマンス映画ポスター風。"],["nanny","空飛ぶ魔法の乳母さん風","傘でふわっと空から降りるクラシカルな魔法の乳母さん風。"],["planet","ペットの惑星風","遠い惑星を舞台にペットたちが主役のSFポスター風。"],["street","下町ミュージカル風","夜の下町で仲間と踊るミュージカル映画ポスター風。"],["princess","おとぎ話プリンセス風","魔法の森、古城、光の粒。"],["magic","魔法学校ファンタジー風","古い城、魔法の光、冒険の始まり。"],["pirate","海賊冒険映画風","大きな船、宝箱、海。怖すぎない。"],["sf","宇宙SF映画風","星空、宇宙船、光る惑星。"],["detective","探偵ミステリー風","霧の街、街灯、虫眼鏡。"],["western","西部劇ポスター風","夕焼けの荒野、木造の街並み。暴力表現は避ける。"],["theater","ミュージカル劇場風","舞台照明、幕、華やかなショー感。"]])},
{id:"animal",label:"動物さんと一緒",icon:PawPrint,description:"動物さんと一緒。",templates:opt([["friend","動物さんと一緒","選んだ動物さんと仲良く一緒にいる夢の動物フォト。"]])},
{id:"panel",label:"うちの子パネル",icon:Info,description:"インフォグラフィック・カレンダー。",templates:opt([["info","インフォグラフィック","世界に一匹だけの希少動物として紹介する本格パネル。"],["calendar","カレンダー","飾りたくなるカレンダーパネル。"]])}
];

const rec=[{title:"ゆゆママのお勧め：夢のミコノス島フォト",image:"/mykonos.png",categoryId:"travel",templateId:"mykonos",text:"白と青とターコイズの夢リゾート。"},{title:"ゆゆママのお勧め：豪華客船ロマンス風",image:"/titanic.png",categoryId:"movie",templateId:"ship",text:"構図・体型固定。顔と毛色だけ本人化。"}];
const cordobaColors=opt([["yuyu","ゆゆママおすすめ","白壁、コバルトブルー鉢、ピンク花多め。"],["colorful","カラフル華やか","色々な鉢と赤・ピンク・紫・黄色の花。"],["chic","上品シック","白壁、黒い鉄格子、深緑、赤い花少なめ。"],["blue","爽やかブルー","青鉢多め、白・水色・淡ピンク花。"]]);
const gender=opt([["male","オス","男の子向けの色・形。"],["female","メス","女の子向けの色・形。"]]);
const taste=opt([["elegant","エレガント","上品でエレガントな服装。"],["sporty","スポーティ","元気でスポーティな服装。"],["casual","カジュアル","自然で可愛いカジュアル服。"],["frill","フリル","フリルを使った可愛い服。"],["lolita","ロリータ","ロリータ風の可愛い服。"],["goth","ゴスロリ","ゴスロリ風の可愛い服。"],["punk","パンク","可愛いパンク風の服。"]]);
const baseOutfits=opt([["keep","なし（元写真のまま）","服は新しく追加せず、元写真の服や自然な姿を維持。"],["auto","おまかせ","世界観に似合う服。"]]);
const summerResort=opt([["swim_m","水着（オス）","男の子向け夏リゾート水着。"],["swim_f","水着（メス）","女の子向け夏リゾート水着。"],["summer_frill","夏向きフリル付きワンピース","軽やかなフリルワンピース。"],["summer_sport","夏向きスポーティセットアップ","爽やかなスポーティセットアップ。"],["summer_casual","夏向けカジュアルセットアップ","夏向けカジュアルセットアップ。"]]);
const kimono=opt([["furisode","振袖着物（友禅）","友禅柄の振袖着物。"],["taisho","大正ロマン風着物","大正ロマン風の着物。"]]);
const vehicleClothes={sl:opt([["conductor","車掌服","可愛い車掌服。"],["station","レトロ駅員風","レトロ駅員風。"]]),retro_airplane:opt([["pilot_jacket","飛行機乗りジャンパー","飛行機乗りジャンパー。"],["pilot","パイロット風ジャケット","パイロット風ジャケット。"]]),flying_bike:opt([["future_rider","未来風ライダースーツ","未来風ライダースーツ。"],["sf_suit","SFジャンプスーツ","SFジャンプスーツ。"]]),flying_car:opt([["future_rider","未来風ライダースーツ","未来風ライダースーツ。"],["sf_suit","SFジャンプスーツ","SFジャンプスーツ。"]]),space_car:opt([["sf_suit","SFジャンプスーツ","SFジャンプスーツ。"],["space_pilot","近未来パイロットスーツ","近未来パイロットスーツ。"]])};
const animalOutfits=opt([["k_auto","おまかせ（きぐるみ）","選んだ動物に合わせた可愛いきぐるみ。",{kigurumi:true}],["keep","なし（元写真のまま）","元写真のまま。"],["kigurumi","きぐるみ","動物モチーフのきぐるみ。",{kigurumi:true}]]);
const headBase=opt([["keep","なし（元写真のまま）","頭装備は追加しない。"],["auto","おまかせ","世界観に合う頭装備。"],["ribbon","リボン","可愛いリボン。"],["frill","フリル帽","可愛いフリル帽。"],["flower_crown","花冠","可愛い花冠。"],["crown","王冠","小さな王冠。"]]);
const headSummer=opt([["straw","麦わら帽子","夏らしい麦わら帽子。"]]);
const headVehicle=opt([["goggles","ゴーグル","可愛いゴーグル。"],["pilot_hat","パイロット帽","可愛いパイロット帽。"]]);
const shoes=opt([["keep","なし（元写真のまま）","靴は追加しない。"],["auto","おまかせ","世界観に合う靴。"],["sandals","サンダル","可愛いサンダル。"],["boots","ブーツ","可愛いブーツ。"]]);
const accessories=opt([["neck","首飾り","可愛い首飾り。"],["bracelet","ブレスレット","小さなブレスレット。"],["bib","スタイ","可愛いスタイ。"]]);
const colors=opt([["auto","おまかせ","世界観に合わせる。"],["pink","ピンク系","ピンク系。"],["blue","水色系","水色系。"],["white","白系","白系。"],["lavender","ラベンダー系","ラベンダー系。"],["mint","ミント系","ミント系。"],["red","赤系","赤系。"]]);
const under=opt([["none","なし","",{block:[]}],["turtle","亀の上","大きな海亀の背中に優しく乗る。",{block:["ski","split"]}],["shell","貝の上","美しく輝く大きな貝の上。",{block:["ski","split"]}],["bottle","瓶の中","幻想的なガラス瓶の中。",{block:["ski","split"]}],["float","浮き輪","浮き輪でぷかぷか。",{block:[]}],["dolphin","イルカの上","優しいイルカの背中。",{block:["ski","split"]}],["orca","オルカの上","優しいオルカの背中。",{block:["ski","split"]}]]);
const summerG=opt([["none","なし",""],["split","スイカ割り","砂浜など安全な場所でスイカ割り。動物の背中では行わない。"],["watermelon","スイカを食べる","スイカを嬉しそうに食べる。"],["ice","ソーダアイス","水色のソーダアイス。"],["ski","水上スキー","水上スキー。"]]);
const fireworkPlaces=opt([["park","遊園地","遊園地から花火を見る。"],["festival","夏祭り","夏祭り会場で花火を見る。"],["shrine","神社の境内","神社の境内から花火を見る。"],["boat","船の上","船の上から花火を見る。"],["beach","ビーチ","ビーチから花火を見る。"]]);
const vibes=opt([["clear","透明感","透明感のある澄んだ仕上がり。"],["dream","夢のよう","夢の中のように幻想的。"],["bright","明るい","明るく晴れやか。"],["clean","清潔感","汚れや生活感のない清潔な仕上がり。"],["book","絵本感","絵本の中のような優しい世界観。"]]);
const animals=[["duck","あひる"],["raccoon","アライグマ"],["alpaca","アルパカ"],["rabbit","うさぎ",["白","茶","黒"]],["wombat","ウォンバット"],["horse","馬"],["cockatiel","オカメインコ",["白","並"]],["duck2","鴨"],["capybara","カピバラ"],["giraffe","キリン"],["bear","くま",["白","茶","黒"]],["koala","コアラ"],["gorilla","ゴリラ"],["deer","鹿"],["zebra","シマウマ"],["swan","白鳥"],["budgie","セキセイインコ",["黄緑","水色","黄色","白"]],["elephant","象"],["cheetah","チーター"],["tiger","虎"],["dino","恐竜",["ティラノ","トリケラ","ブラキオ","ステゴ"]],["panda","パンダ"],["shoebill","ハシビロコウ"],["hedgehog","ハリネズミ"],["leopard","豹",["黄","黒"]],["sheep","羊"],["meerkat","ミーアキャット"],["goat","ヤギ"],["lion","ライオン"],["redpanda","レッサーパンダ"]].map(([id,label,colors])=>({id,label,colors}));
const monthThemes={1:"お正月。和室、床の間、正月飾り、梅、障子から朝日、羽子板、鏡餅、金粉。男の子は青系着物、女の子はピンク系着物。",2:"雪遊び。スノーボード、雪の結晶、雪煙、小さい雪だるま。男の子は青系、女の子はピンク系のスノボスーツとゴーグル。",3:"ひな祭り。お雛様の祭壇、桃の花、三色団子、甘酒、ひなあられ。",4:"満開の桜。桜並木、桜吹雪多め、桜絨毯、青空固定。",5:"こいのぼりと初夏ピクニック。芝生、ピクニックシート、シャボン玉。女の子はピンク花、男の子は水色花。",6:"梅雨の夢池。オオオニバスの葉っぱの上、周囲にスイレン、お天気雨、紫陽花控えめ、雨粒キラキラ。体は人形形態、腰が後ろに出た犬の二足立ちは禁止。手は丸いペットらしい手。",7:"ひまわり畑。満開のひまわり、青空、入道雲、夏の風。",8:"花火大会。男の子は紺色、女の子はピンクの浴衣。提灯、金魚すくい小物。",9:"秋の甘味と十五夜。栗、かぼちゃ、お芋、お月さま、ススキ。",10:"ハロウィン。衣装はミイラ・魔女・パンプキンきぐるみ・吸血鬼・アリス。背景は衣装連動。",11:"秋の紅葉。紅葉のベンチで読書。クラシカルな本、落ち葉。",12:"クリスマス。サンタ服、雪の結晶、赤い実、高級フェイクファー、ツリー、プレゼント、クマぬいぐるみ、暖炉、イルミ、雪。"};
function days(y,m){const last=new Date(y,m,0).getDate(),w=["日","月","火","水","木","金","土"];return Array.from({length:last},(_,i)=>{const d=i+1;return `${d}(${w[new Date(y,m-1,d).getDay()]})`}).join(" / ")}

function App(){
 const[cat,setCat]=useState("travel"),[tpl,setTpl]=useState({travel:"mykonos",summer:"beach",vehicle:"sl",movie:"ship",animal:"friend",panel:"info"}),[hide,setHide]=useState(false),[copied,setCopied]=useState(false);
 const[customPlace,setCustomPlace]=useState(""),[customVehicle,setCustomVehicle]=useState(""),[cordoba,setCordoba]=useState("yuyu"),[g,setG]=useState("female"),[ta,setTa]=useState("frill"),[customOutfit,setCustomOutfit]=useState(""),[head,setHead]=useState("auto"),[customHead,setCustomHead]=useState(""),[shoe,setShoe]=useState("keep"),[customShoe,setCustomShoe]=useState(""),[acc,setAcc]=useState([]),[customAcc,setCustomAcc]=useState(""),[color,setColor]=useState("auto"),[customColor,setCustomColor]=useState(""),[lightId,setLight]=useState("auto"),[ratioId,setRatio]=useState("r45"),[ratioH,setRatioH]=useState(""),[ratioW,setRatioW]=useState(""),[underId,setUnder]=useState("none"),[customGimmick,setCustomGimmick]=useState(""),[summerId,setSummer]=useState("none"),[firePlace,setFirePlace]=useState("festival"),[vibeIds,setVibes]=useState(["clear","dream","clean"]),[title,setTitle]=useState(""),[animalId,setAnimal]=useState("panda"),[animalColor,setAnimalColor]=useState(""),[customAnimal,setCustomAnimal]=useState(""),[fields,setFields]=useState({name:"",nick:"",birthday:"",age:"",sex:"",species:"",personality:"",likes:"",dislikes:"",walkTime:"",place:"",food:"",charm:"",skill:"",comment:""}),[year,setYear]=useState(new Date().getFullYear()),[month,setMonth]=useState(new Date().getMonth()+1),[paperId,setPaper]=useState("sns"),[dirId,setDir]=useState("portrait"),[halloween,setHalloween]=useState("魔女");
 const category=by(categories,cat),template=by(category.templates,tpl[cat]),li=by(light,lightId),ratio=by(ratios,ratioId),un=by(under,underId),su=by(summerG,summerId),animal=by(animals,animalId),Icon=category.icon,isPanel=cat==="panel",isCal=isPanel&&template.id==="calendar",isInfo=isPanel&&template.id==="info";
 const headOptions=[...headBase,...((cat==="summer"||template.id==="mykonos")?headSummer:[]),...(cat==="vehicle"?headVehicle:[])];
 const outfitOptions=cat==="animal"?animalOutfits:cat==="travel"&&template.id==="kyoto"?[...baseOutfits,...kimono]:cat==="travel"&&template.id==="mykonos"?[...baseOutfits,...summerResort]:cat==="travel"&&["paris","london","alsace","petite","romantic","venice","mont","castle"].includes(template.id)?[...baseOutfits,...opt([["retro","レトロ旅行服","レトロ旅行服。"]])]:cat==="vehicle"?[...baseOutfits,...(vehicleClothes[template.id]||[])]:baseOutfits;
 const outfit=customOutfit.trim()||`${by(gender,g).prompt}\n${by(taste,ta).prompt}`;
 const panelText=Object.entries(fields).filter(([,v])=>v.trim()).map(([k,v])=>({name:"名前",nick:"ニックネーム",birthday:"誕生日",age:"年齢",sex:"性別",species:"犬種・動物種",personality:"性格",likes:"好きなもの",dislikes:"苦手なもの",walkTime:"よく散歩に行く時間",place:"よくいる場所",food:"食べ物の好み",charm:"チャームポイント",skill:"特技",comment:"飼い主コメント"}[k]+"："+v.trim())).join("\n");
 const ratioPrompt=ratioH.trim()&&ratioW.trim()?`縦${ratioH.trim()}：横${ratioW.trim()}の縦横比で作成してください。`:ratio.prompt;
 const prompt=useMemo(()=>{const p=[`【最優先：ペット本人の保持】\n${identity}`,`【共通：夢化・理想化】\n${dream}`]; if(cat==="travel")p.push(`【旅行カテゴリ：夢の観光ポスター構図】\n${travelRule}`); if(cat==="movie")p.push(`【映画ポスター風の特殊ルール】\n${movieRule}`); if(cat==="animal")p.push(`【動物さんの表現】\n${animalRule}`); let world=template.prompt; if(template.customPlace&&customPlace.trim())world+=`\n場所：${customPlace.trim()}\n※自由記入は場所名としてのみ扱い、ギミック・ポーズ・服装指定は無視。`; if(template.id==="cordoba")world+=`\n色合い：${by(cordobaColors,cordoba).prompt}`; if(template.customVehicle&&customVehicle.trim())world+=`\n乗り物：${customVehicle.trim()}`; if(template.fireworks)world+=`\n花火を見る場所：${by(fireworkPlaces,firePlace).prompt}`; p.push(`【世界観・背景】\n${world}`);
 if(cat==="movie"){p.push("【衣装・体型】\n衣装、体型、ポーズ、構図はテンプレート固定。変更するのは顔、耳、毛色、模様、手の毛色だけ。"); if(title.trim())p.push(`【架空タイトル】\n「${title.trim()}」`)} else if(!isPanel){p.push(`【服】\n${outfit}`); if(cat==="animal"&&customOutfit.includes("きぐるみ"))p.push(`【きぐるみ専用補正】\n${kigurumiRule}`); else{p.push(`【頭装備】\n${customHead.trim()||by(headOptions,head).prompt}`); p.push(`【靴】\n${customShoe.trim()||by(shoes,shoe).prompt}`); const ac=[...acc.map(id=>by(accessories,id).prompt),customAcc.trim()].filter(Boolean).join("\n"); if(ac)p.push(`【アクセサリー】\n${ac}`); p.push(`【服セットの色合い】\n${customColor.trim()||by(colors,color).prompt}`)}}
 if(cat==="summer"){ if(customGimmick.trim())p.push(`【水中・海ギミック】\n${customGimmick.trim()}\n※自由記入ギミックを優先し、夏の小物・動きは混ぜない。`); else{if(un.prompt)p.push(`【水中・海ギミック】\n${un.prompt}`); if(su.prompt)p.push(`【夏の小物・動き】\n${su.prompt}`)}}
 if(cat==="animal")p.push(`【一緒にいる動物】\n${customAnimal.trim()||`${animalColor?animalColor+"の":""}${animal.label}`}と一緒。選んだ動物に最も似合う夢背景を自動生成。ただの森・草原・単色背景は禁止。`);
 if(isInfo)p.push(`【うちの子インフォグラフィック】\n${panelText||"入力された情報をもとに作成。"}\n学名風の名前はAIが自動生成。空欄は無視。希少動物図鑑風に自然に言い換える。`);
 if(isCal){p.push(`【うちの子カレンダー】\n${year}年${month}月のカレンダー。\n月別テーマ：${monthThemes[Number(month)]||"季節感のある可愛いカレンダー。"}\nカレンダー表：${days(Number(year),Number(month))}\n日本の祝祭日は正確な公的データを参照し、該当日には祝日名を明記。日曜と祝日は赤、土曜は青。曜日と日付を創作しない。\nサイズ：${by(paper,paperId).label}、${by(dirs,dirId).label}向き。`); if(Number(month)===10)p.push(`【ハロウィン衣装】\n性別：${by(gender,g).label}\n衣装：${halloween}`); if([1,2,5,8,12].includes(Number(month)))p.push(`【性別による衣装・配色】\n性別：${by(gender,g).label}`)}
 p.push(`【雰囲気】\n${vibeIds.map(id=>by(vibes,id).prompt).join("\n")}\n${darkRule}`); p.push(`【光・明るさ】\n${li.prompt}`); p.push(`【縦横比】\n${ratioPrompt}`); p.push("【仕上げ】\n高品質、可愛いペットポートレート、清潔感、透明感、理想化された夢の世界。"); return p.join("\n\n")},[cat,template,customPlace,customVehicle,cordoba,firePlace,title,outfit,customHead,head,customShoe,shoe,acc,customAcc,customColor,color,customGimmick,un,su,animal,animalColor,customAnimal,isInfo,isCal,panelText,year,month,paperId,dirId,halloween,g,vibeIds,li,ratioPrompt]);
 const copy=async(t=prompt)=>{await navigator.clipboard.writeText(t);setCopied(true);setTimeout(()=>setCopied(false),1400)}; const togAcc=id=>setAcc(a=>a.includes(id)?a.filter(x=>x!==id):[...a,id]); const togV=id=>setVibes(a=>a.includes(id)?a.filter(x=>x!==id):a.length>=3?a:[...a,id]); const changeCat=id=>{setCat(id);setTpl(cur=>({...cur,[id]:by(categories,id).templates[0].id}))}; const n=cat==="summer"||cat==="animal"?9:cat==="panel"?4:cat==="movie"?4:8;
 return <main className="page"><div className="blob blob-pink"/><div className="blob blob-violet"/><div className="blob blob-blue"/><div className="dots"/><div className="container"><header className="hero"><div className="badge"><Sparkles size={18}/>Yuyu Mama Dream Prompt Studio</div><h1>ゆゆママの夢プロンプト工房（汎用版）</h1><p className="subtitle">うちの子を主役に、世界旅行・夏の海・乗り物・映画ポスター・うちの子パネルを作る工房です。</p><div className="hero-image"><img src={heroImageUrl} alt="トップ画像"/></div><a className="sister-link" href={sisterSiteUrl} target="_blank" rel="noreferrer"><LinkIcon size={16}/>姉妹サイト：ゆゆ姫の夢かわプロンプト工房はこちら</a></header>
 {!hide&&<section className="card recommend-card"><div className="card-head"><h2><Sparkles size={19}/>ゆゆママのお勧め</h2><button className="outline-button" onClick={()=>setHide(true)}><X size={16}/>閉じる</button></div><div className="recommend-grid">{rec.map(r=><article className="recommend-item" key={r.title}><img src={r.image} alt={r.title}/><div><strong>{r.title}</strong><small>{r.text}</small><button className="main-button mini" onClick={()=>{setCat(r.categoryId);setTpl(cur=>({...cur,[r.categoryId]:r.templateId}));copy()}}>このおすすめを使う</button></div></article>)}</div></section>}
 <div className="grid"><section className="left"><div className="notice"><strong>この工房の方針</strong><span>清潔感・透明感・夢感を大切にした「うちの子の理想世界」を作ります。</span></div><section className="card"><h2><Sparkles size={19}/>1. ジャンルを選択</h2><div className="choice-grid">{categories.map(c=>{const I=c.icon;return <button className={`big-choice ${cat===c.id?"active-soft":""}`} onClick={()=>changeCat(c.id)} key={c.id}><strong><I size={18}/>{c.label}</strong><span>{c.description}</span></button>})}</div></section>
 {!(cat==="panel"&&template.id==="info")&&<section className="card"><h2><Icon size={19}/>2. テンプレを選択</h2><div className="chips">{category.templates.map(t=><button className={`chip ${template.id===t.id?"active":""}`} onClick={()=>setTpl(cur=>({...cur,[cat]:t.id}))} key={t.id}>{t.label}</button>)}</div>{template.customPlace&&<><label>自由記入欄</label><p className="selected">※場所のみ記入。ギミック・ポーズ・服装指定などは無視。</p><input value={customPlace} onChange={e=>setCustomPlace(e.target.value)} placeholder="例：フィレンツェ、ドバイ"/></>}{template.customVehicle&&<><label>乗り物自由記入</label><input value={customVehicle} onChange={e=>setCustomVehicle(e.target.value)} placeholder="例：かぼちゃの馬車"/></>}{template.id==="cordoba"&&<><label>パティオの色合い</label><div className="chips">{cordobaColors.map(x=><button className={`chip ${cordoba===x.id?"active":""}`} onClick={()=>setCordoba(x.id)} key={x.id}>{x.label}</button>)}</div></>}{template.fireworks&&<><label>花火を見る場所</label><div className="chips">{fireworkPlaces.map(x=><button className={`chip ${firePlace===x.id?"active":""}`} onClick={()=>setFirePlace(x.id)} key={x.id}>{x.label}</button>)}</div></>}</section>}
 {!isPanel&&cat!=="movie"&&<section className="card"><h2><Shirt size={19}/>3. 服</h2><label>性別</label><div className="chips">{gender.map(x=><button className={`chip ${g===x.id?"active":""}`} onClick={()=>setG(x.id)} key={x.id}>{x.label}</button>)}</div><label>服の方向性</label><div className="chips">{taste.map(x=><button disabled={!!customOutfit.trim()} className={`chip ${ta===x.id?"active":""}`} onClick={()=>setTa(x.id)} key={x.id}>{x.label}</button>)}</div><label>服の自由記入</label><input value={customOutfit} onChange={e=>setCustomOutfit(e.target.value)} placeholder="例：水色チェックのフリルワンピース"/><div className="chips">{outfitOptions.map(o=><button disabled={!!customOutfit.trim()} className="chip" key={o.id} onClick={()=>setCustomOutfit(o.prompt)}>{o.label}</button>)}</div><h2>4. 頭装備</h2><div className="chips">{headOptions.map(h=><button disabled={!!customHead.trim()} className={`chip ${head===h.id?"active":""}`} onClick={()=>setHead(h.id)} key={h.id}>{h.label}</button>)}</div><label>頭装備の自由記入</label><input value={customHead} onChange={e=>setCustomHead(e.target.value)}/><h2>5. 靴</h2><div className="chips">{shoes.map(s=><button disabled={!!customShoe.trim()} className={`chip ${shoe===s.id?"active":""}`} onClick={()=>setShoe(s.id)} key={s.id}>{s.label}</button>)}</div><label>靴の自由記入</label><input value={customShoe} onChange={e=>setCustomShoe(e.target.value)}/><h2>6. アクセサリー</h2><div className="chips">{accessories.map(a=><button className={`chip ${acc.includes(a.id)?"active":""}`} onClick={()=>togAcc(a.id)} key={a.id}>{a.label}</button>)}</div><label>アクセサリー自由記入</label><input value={customAcc} onChange={e=>setCustomAcc(e.target.value)}/><h2>7. 服セットの色合い</h2><div className="chips">{colors.map(c=><button disabled={!!customColor.trim()} className={`chip ${color===c.id?"active":""}`} onClick={()=>setColor(c.id)} key={c.id}>{c.label}</button>)}</div><label>色合い自由記入</label><input value={customColor} onChange={e=>setCustomColor(e.target.value)}/></section>}
 {cat==="movie"&&<section className="card"><h2><Film size={19}/>3. 架空タイトル</h2><input value={title} onChange={e=>setTitle(e.target.value)} placeholder="例：白雪ゆゆ姫"/></section>}
 {cat==="summer"&&<section className="card"><h2><Waves size={19}/>8. 夏・水中ギミック</h2><label>ギミック自由記入</label><input value={customGimmick} onChange={e=>setCustomGimmick(e.target.value)}/><label>水中・海ギミック</label><div className="chips">{under.map(u=><button disabled={!!customGimmick.trim()} className={`chip ${underId===u.id?"active":""}`} onClick={()=>{setUnder(u.id);if((u.block||[]).includes(summerId))setSummer("none")}} key={u.id}>{u.label}</button>)}</div><label>夏の小物・動き</label><div className="chips">{summerG.map(s=><button disabled={!!customGimmick.trim()||(un.block||[]).includes(s.id)} className={`chip ${summerId===s.id?"active":""}`} onClick={()=>setSummer(s.id)} key={s.id}>{s.label}</button>)}</div></section>}
 {cat==="animal"&&<section className="card"><h2><PawPrint size={19}/>8. 動物を選択（五十音順）</h2><div className="animal-list">{animals.map(a=><div className="animal-row" key={a.id}><button className={`animal-name ${animal.id===a.id?"active":""}`} onClick={()=>{setAnimal(a.id);setAnimalColor(a.colors?.[0]||"")}}>{a.label}</button>{a.colors&&<span>{a.colors.map(color=><label className="radio-inline" key={color}><input type="radio" checked={animal.id===a.id&&animalColor===color} onChange={()=>{setAnimal(a.id);setAnimalColor(color)}}/>{color}</label>)}</span>}</div>)}</div><label>自由記入</label><input value={customAnimal} onChange={e=>setCustomAnimal(e.target.value)} placeholder="例：白いフェネック"/></section>}
 {isInfo&&<section className="card"><h2><Info size={19}/>2. プロフィール情報</h2><p className="selected">学名風はAIが自動生成。空欄は無効。</p><div className="form-grid">{Object.entries({name:"名前",nick:"ニックネーム",birthday:"誕生日",age:"年齢",sex:"性別",species:"犬種・動物種",personality:"性格",likes:"好きなもの",dislikes:"苦手なもの",walkTime:"よく散歩に行く時間",place:"よくいる場所",food:"食べ物の好み",charm:"チャームポイント",skill:"特技",comment:"飼い主コメント"}).map(([k,l])=><label key={k}>{l}<input value={fields[k]} onChange={e=>setFields(v=>({...v,[k]:e.target.value}))}/></label>)}</div></section>}
 {isCal&&<section className="card"><h2><Info size={19}/>3. カレンダー設定</h2><div className="form-grid"><label>年<input type="number" value={year} onChange={e=>setYear(e.target.value)}/></label><label>月<input type="number" min="1" max="12" value={month} onChange={e=>setMonth(e.target.value)}/></label></div><label>性別</label><div className="chips">{gender.map(x=><button className={`chip ${g===x.id?"active":""}`} onClick={()=>setG(x.id)} key={x.id}>{x.label}</button>)}</div><label>サイズ</label><div className="chips">{paper.map(x=><button className={`chip ${paperId===x.id?"active":""}`} onClick={()=>setPaper(x.id)} key={x.id}>{x.label}</button>)}</div><label>向き</label><div className="chips">{dirs.map(x=><button className={`chip ${dirId===x.id?"active":""}`} onClick={()=>setDir(x.id)} key={x.id}>{x.label}</button>)}</div>{Number(month)===10&&<><label>ハロウィン衣装</label><div className="chips">{["ミイラ","魔女","パンプキンきぐるみ","吸血鬼","アリス"].map(x=><button className={`chip ${halloween===x?"active":""}`} onClick={()=>setHalloween(x)} key={x}>{x}</button>)}</div></>}</section>}
 <section className="card"><h2><Heart size={19}/>{n}. 雰囲気（3つまで選択可能）</h2><div className="chips">{vibes.map(v=><button className={`chip ${vibeIds.includes(v.id)?"active":""}`} onClick={()=>togV(v.id)} key={v.id}>{v.label}</button>)}</div></section><section className="card"><h2>{n+1}. 光・明るさ</h2><div className="chips">{light.map(l=><button className={`chip ${lightId===l.id?"active":""}`} onClick={()=>setLight(l.id)} key={l.id}>{l.label}</button>)}</div></section><section className="card"><h2>{n+2}. 縦横比</h2><div className="chips">{ratios.map(r=><button disabled={!!ratioH.trim()||!!ratioW.trim()} className={`chip ${ratioId===r.id?"active":""}`} onClick={()=>setRatio(r.id)} key={r.id}>{r.label}</button>)}</div><div className="ratio-inputs"><label>縦<input value={ratioH} onChange={e=>setRatioH(e.target.value)} placeholder="例：9"/></label><span>：</span><label>横<input value={ratioW} onChange={e=>setRatioW(e.target.value)} placeholder="例：16"/></label></div></section></section><aside className="right"><section className="card result-card"><div className="card-head"><h2><ImageIcon size={19}/>生成プロンプト</h2><button className="main-button" onClick={()=>copy()}>{copied?<CheckCircle2 size={16}/>:<Copy size={16}/>} {copied?"コピー済み":"コピー"}</button></div><div className="message warn"><AlertCircle size={16}/>画像生成時は、このプロンプトと一緒にペット写真をアップロードしてください。</div><textarea value={prompt} readOnly/></section></aside></div></div></main>}
createRoot(document.getElementById("root")).render(<App/>);
